#ifndef TASKLISTCONSTS_H
#define TASKLISTCONSTS_H

#define TASK_LIST_MAX_COLS 34
#define TASK_LIST_MAX_ROWS 10


#define TASK_LIST_TITLE_SIZE 6
#define TASK_LIST_DATE_SIZE 3
#define TASK_LIST_TEXT_SIZE 4

#define TASK_LIST_WIDTH 790
#define TASK_LIST_HEIGHT 320

#define TASK_LIST_TEXT_WIDTH 23
#define TASK_LIST_TEXT_HEIGHT 30

#define TASK_LIST_PADDING_X 112
#define TASK_LIST_PADDING_Y 150

#endif